name: Build & Deploy ASP.NET Core 9 to Azure Web App (progaaplicada)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  WEBAPP_NAME: "progaaplicada" # nombre del App Service
  DOTNET_VERSION: "9.0.x"
  PROJECT_PATH: "." # cambia a "src/MyApi" si tu csproj está en subcarpeta
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      # Opcional: tests
      # - name: Test
      #   run: dotnet test tests/YourTests.csproj -c Release --no-build

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          # slot-name: "Production"  # opcional, por defecto es Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
