name: Build & Deploy ASP.NET Core 9 to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  WEBAPP_NAME: "progaaplicada"
  DOTNET_VERSION: "9.0.x"
  PROJECT_PATH: "." # cambia si tu .csproj está en subcarpeta
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Show publish contents (debug)
        run: |
          echo "Published files:"
          ls -la ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }} # << deploy JUST the published output
